name: Crystal CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * MON"

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: crystallang/crystal
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        crystal --version
        shards install
    - name: Run tests
      run: crystal spec --verbose
    - name: Run linter
      run: bin/ameba
